// ═══════════════════════════════════════════════════════════════════════════
// TableQuizz - French Conjugation Data
// ═══════════════════════════════════════════════════════════════════════════

const PRONOUNS = [
  { fr: "je", en: "I", elided: "j'" },
  { fr: "tu", en: "you (informal)", elided: null },
  { fr: "il/elle/on", en: "he/she/one", elided: null },
  { fr: "nous", en: "we", elided: null },
  { fr: "vous", en: "you (formal/pl.)", elided: null },
  { fr: "ils/elles", en: "they", elided: null },
];

const TENSES = {
  present: {
    name: "Présent",
    nameEn: "Present",
    description: "Actions happening now, habits, general truths",
    descriptionFr: "Actions actuelles, habitudes, vérités générales",
    color: "#f8bbd9",
    whenToUse: [
      { fr: "Actions en cours", en: "Current actions" },
      { fr: "Habitudes", en: "Habits" },
      { fr: "Vérités générales", en: "General truths" },
      { fr: "Futur proche (avec contexte)", en: "Near future (with context)" },
    ],
    examples: [
      { fr: "Je parle français.", en: "I speak French." },
      { fr: "Elle mange une pomme.", en: "She is eating an apple." },
      { fr: "Le soleil se lève à l'est.", en: "The sun rises in the east." },
      { fr: "Demain, je pars en vacances.", en: "Tomorrow, I leave for vacation." },
    ],
  },
  passeCompose: {
    name: "Passé composé",
    nameEn: "Past (completed)",
    description: "Completed actions in the past",
    descriptionFr: "Actions terminées dans le passé",
    color: "#ce93d8",
    whenToUse: [
      { fr: "Actions terminées", en: "Completed actions" },
      { fr: "Événements ponctuels", en: "Single events" },
      { fr: "Séquence d'actions", en: "Sequence of actions" },
      { fr: "Changement soudain", en: "Sudden change" },
    ],
    examples: [
      { fr: "J'ai mangé une pizza hier.", en: "I ate a pizza yesterday." },
      { fr: "Elle est partie à 8 heures.", en: "She left at 8 o'clock." },
      { fr: "Nous avons visité Paris.", en: "We visited Paris." },
      { fr: "Il a commencé à pleuvoir.", en: "It started to rain." },
    ],
  },
  imparfait: {
    name: "Imparfait",
    nameEn: "Imperfect",
    description: "Ongoing or habitual past actions, descriptions",
    descriptionFr: "Actions continues ou habituelles dans le passé",
    color: "#b39ddb",
    whenToUse: [
      { fr: "Actions habituelles passées", en: "Past habits" },
      { fr: "Descriptions", en: "Descriptions" },
      { fr: "Actions en cours (interrompues)", en: "Ongoing actions (interrupted)" },
      { fr: "Contexte / arrière-plan", en: "Background / context" },
    ],
    examples: [
      { fr: "Quand j'étais petit, je jouais au foot.", en: "When I was little, I used to play soccer." },
      { fr: "Il faisait beau ce jour-là.", en: "The weather was nice that day." },
      { fr: "Je dormais quand tu as appelé.", en: "I was sleeping when you called." },
      { fr: "Elle avait les cheveux longs.", en: "She had long hair." },
    ],
  },
  futurSimple: {
    name: "Futur simple",
    nameEn: "Future",
    description: "Actions that will happen",
    descriptionFr: "Actions qui vont se produire",
    color: "#90caf9",
    whenToUse: [
      { fr: "Actions futures certaines", en: "Certain future actions" },
      { fr: "Promesses", en: "Promises" },
      { fr: "Prédictions", en: "Predictions" },
      { fr: "Projets", en: "Plans" },
    ],
    examples: [
      { fr: "Demain, j'irai au cinéma.", en: "Tomorrow, I will go to the cinema." },
      { fr: "Je te promets que je viendrai.", en: "I promise I will come." },
      { fr: "Il pleuvra ce week-end.", en: "It will rain this weekend." },
      { fr: "Nous achèterons une maison.", en: "We will buy a house." },
    ],
  },
  conditionnelPresent: {
    name: "Conditionnel présent",
    nameEn: "Conditional",
    description: "Would do something, polite requests",
    descriptionFr: "Actions conditionnelles, demandes polies",
    color: "#80deea",
    whenToUse: [
      { fr: "Politesse", en: "Politeness" },
      { fr: "Souhait", en: "Wishes" },
      { fr: "Hypothèse (si + imparfait)", en: "Hypothetical (si + imperfect)" },
      { fr: "Conseil", en: "Advice" },
    ],
    examples: [
      { fr: "Je voudrais un café, s'il vous plaît.", en: "I would like a coffee, please." },
      { fr: "J'aimerais voyager au Japon.", en: "I would like to travel to Japan." },
      { fr: "Si j'étais riche, j'achèterais un château.", en: "If I were rich, I would buy a castle." },
      { fr: "Tu devrais dormir plus.", en: "You should sleep more." },
    ],
  },
  subjonctifPresent: {
    name: "Subjonctif présent",
    nameEn: "Subjunctive",
    description: "Wishes, doubts, emotions, necessities",
    descriptionFr: "Souhaits, doutes, émotions, nécessités",
    color: "#a5d6a7",
    whenToUse: [
      { fr: "Après 'que' + émotion", en: "After 'que' + emotion" },
      { fr: "Après 'que' + volonté", en: "After 'que' + will/want" },
      { fr: "Après 'que' + doute", en: "After 'que' + doubt" },
      { fr: "Expressions: il faut que, bien que...", en: "Expressions: il faut que, bien que..." },
    ],
    examples: [
      { fr: "Je suis content que tu sois là.", en: "I'm happy that you are here." },
      { fr: "Je veux que tu viennes.", en: "I want you to come." },
      { fr: "Je doute qu'il puisse venir.", en: "I doubt he can come." },
      { fr: "Il faut que tu fasses tes devoirs.", en: "You must do your homework." },
    ],
  },
};

// Verb group definitions
const VERB_GROUPS = {
  group1: {
    name: "1er Groupe",
    nameEn: "First Group",
    rule: "Verbes en -ER (sauf aller)",
    ruleEn: "Verbs ending in -ER (except aller)",
    color: "#f8bbd9",
  },
  group2: {
    name: "2ème Groupe",
    nameEn: "Second Group",
    rule: "Verbes en -IR avec -issons",
    ruleEn: "Verbs ending in -IR with -issons",
    color: "#ce93d8",
  },
  group3: {
    name: "3ème Groupe",
    nameEn: "Third Group",
    rule: "Tous les verbes irréguliers",
    ruleEn: "All irregular verbs",
    color: "#b39ddb",
  },
};

const VERBS = {
  etre: {
    infinitive: "être",
    english: "to be",
    group: "3ème groupe",
    groupNum: 3,
    importance: 1,
    isAuxiliary: true,
    tenses: {
      present: ["suis", "es", "est", "sommes", "êtes", "sont"],
      passeCompose: ["ai été", "as été", "a été", "avons été", "avez été", "ont été"],
      imparfait: ["étais", "étais", "était", "étions", "étiez", "étaient"],
      futurSimple: ["serai", "seras", "sera", "serons", "serez", "seront"],
      conditionnelPresent: ["serais", "serais", "serait", "serions", "seriez", "seraient"],
      subjonctifPresent: ["sois", "sois", "soit", "soyons", "soyez", "soient"],
    },
    tensesEn: {
      present: ["am", "are", "is", "are", "are", "are"],
      passeCompose: ["was/have been", "were/have been", "was/has been", "were/have been", "were/have been", "were/have been"],
      imparfait: ["was (being)", "were (being)", "was (being)", "were (being)", "were (being)", "were (being)"],
      futurSimple: ["will be", "will be", "will be", "will be", "will be", "will be"],
      conditionnelPresent: ["would be", "would be", "would be", "would be", "would be", "would be"],
      subjonctifPresent: ["(that I) be", "(that you) be", "(that he) be", "(that we) be", "(that you) be", "(that they) be"],
    },
  },
  avoir: {
    infinitive: "avoir",
    english: "to have",
    group: "3ème groupe",
    groupNum: 3,
    importance: 1,
    startsWithVowel: true,
    isAuxiliary: true,
    tenses: {
      present: ["ai", "as", "a", "avons", "avez", "ont"],
      passeCompose: ["ai eu", "as eu", "a eu", "avons eu", "avez eu", "ont eu"],
      imparfait: ["avais", "avais", "avait", "avions", "aviez", "avaient"],
      futurSimple: ["aurai", "auras", "aura", "aurons", "aurez", "auront"],
      conditionnelPresent: ["aurais", "aurais", "aurait", "aurions", "auriez", "auraient"],
      subjonctifPresent: ["aie", "aies", "ait", "ayons", "ayez", "aient"],
    },
    tensesEn: {
      present: ["have", "have", "has", "have", "have", "have"],
      passeCompose: ["had/have had", "had/have had", "had/has had", "had/have had", "had/have had", "had/have had"],
      imparfait: ["had/used to have", "had/used to have", "had/used to have", "had/used to have", "had/used to have", "had/used to have"],
      futurSimple: ["will have", "will have", "will have", "will have", "will have", "will have"],
      conditionnelPresent: ["would have", "would have", "would have", "would have", "would have", "would have"],
      subjonctifPresent: ["(that I) have", "(that you) have", "(that he) have", "(that we) have", "(that you) have", "(that they) have"],
    },
  },
  aller: {
    infinitive: "aller",
    english: "to go",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    startsWithVowel: true,
    usesEtre: true,
    tenses: {
      present: ["vais", "vas", "va", "allons", "allez", "vont"],
      passeCompose: ["suis allé(e)", "es allé(e)", "est allé(e)", "sommes allé(e)s", "êtes allé(e)(s)", "sont allé(e)s"],
      imparfait: ["allais", "allais", "allait", "allions", "alliez", "allaient"],
      futurSimple: ["irai", "iras", "ira", "irons", "irez", "iront"],
      conditionnelPresent: ["irais", "irais", "irait", "irions", "iriez", "iraient"],
      subjonctifPresent: ["aille", "ailles", "aille", "allions", "alliez", "aillent"],
    },
    tensesEn: {
      present: ["go", "go", "goes", "go", "go", "go"],
      passeCompose: ["went", "went", "went", "went", "went", "went"],
      imparfait: ["was going/used to go", "were going/used to go", "was going/used to go", "were going/used to go", "were going/used to go", "were going/used to go"],
      futurSimple: ["will go", "will go", "will go", "will go", "will go", "will go"],
      conditionnelPresent: ["would go", "would go", "would go", "would go", "would go", "would go"],
      subjonctifPresent: ["(that I) go", "(that you) go", "(that he) go", "(that we) go", "(that you) go", "(that they) go"],
    },
  },
  faire: {
    infinitive: "faire",
    english: "to do / to make",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["fais", "fais", "fait", "faisons", "faites", "font"],
      passeCompose: ["ai fait", "as fait", "a fait", "avons fait", "avez fait", "ont fait"],
      imparfait: ["faisais", "faisais", "faisait", "faisions", "faisiez", "faisaient"],
      futurSimple: ["ferai", "feras", "fera", "ferons", "ferez", "feront"],
      conditionnelPresent: ["ferais", "ferais", "ferait", "ferions", "feriez", "feraient"],
      subjonctifPresent: ["fasse", "fasses", "fasse", "fassions", "fassiez", "fassent"],
    },
    tensesEn: {
      present: ["do/make", "do/make", "does/makes", "do/make", "do/make", "do/make"],
      passeCompose: ["did/made", "did/made", "did/made", "did/made", "did/made", "did/made"],
      imparfait: ["was doing/used to do", "were doing/used to do", "was doing/used to do", "were doing/used to do", "were doing/used to do", "were doing/used to do"],
      futurSimple: ["will do/make", "will do/make", "will do/make", "will do/make", "will do/make", "will do/make"],
      conditionnelPresent: ["would do/make", "would do/make", "would do/make", "would do/make", "would do/make", "would do/make"],
      subjonctifPresent: ["(that I) do", "(that you) do", "(that he) do", "(that we) do", "(that you) do", "(that they) do"],
    },
  },
  pouvoir: {
    infinitive: "pouvoir",
    english: "can / to be able to",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"],
      passeCompose: ["ai pu", "as pu", "a pu", "avons pu", "avez pu", "ont pu"],
      imparfait: ["pouvais", "pouvais", "pouvait", "pouvions", "pouviez", "pouvaient"],
      futurSimple: ["pourrai", "pourras", "pourra", "pourrons", "pourrez", "pourront"],
      conditionnelPresent: ["pourrais", "pourrais", "pourrait", "pourrions", "pourriez", "pourraient"],
      subjonctifPresent: ["puisse", "puisses", "puisse", "puissions", "puissiez", "puissent"],
    },
    tensesEn: {
      present: ["can", "can", "can", "can", "can", "can"],
      passeCompose: ["could/was able to", "could/were able to", "could/was able to", "could/were able to", "could/were able to", "could/were able to"],
      imparfait: ["could/was able to", "could/were able to", "could/was able to", "could/were able to", "could/were able to", "could/were able to"],
      futurSimple: ["will be able to", "will be able to", "will be able to", "will be able to", "will be able to", "will be able to"],
      conditionnelPresent: ["could/would be able to", "could/would be able to", "could/would be able to", "could/would be able to", "could/would be able to", "could/would be able to"],
      subjonctifPresent: ["(that I) can", "(that you) can", "(that he) can", "(that we) can", "(that you) can", "(that they) can"],
    },
  },
  vouloir: {
    infinitive: "vouloir",
    english: "to want",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["veux", "veux", "veut", "voulons", "voulez", "veulent"],
      passeCompose: ["ai voulu", "as voulu", "a voulu", "avons voulu", "avez voulu", "ont voulu"],
      imparfait: ["voulais", "voulais", "voulait", "voulions", "vouliez", "voulaient"],
      futurSimple: ["voudrai", "voudras", "voudra", "voudrons", "voudrez", "voudront"],
      conditionnelPresent: ["voudrais", "voudrais", "voudrait", "voudrions", "voudriez", "voudraient"],
      subjonctifPresent: ["veuille", "veuilles", "veuille", "voulions", "vouliez", "veuillent"],
    },
    tensesEn: {
      present: ["want", "want", "wants", "want", "want", "want"],
      passeCompose: ["wanted", "wanted", "wanted", "wanted", "wanted", "wanted"],
      imparfait: ["wanted/used to want", "wanted/used to want", "wanted/used to want", "wanted/used to want", "wanted/used to want", "wanted/used to want"],
      futurSimple: ["will want", "will want", "will want", "will want", "will want", "will want"],
      conditionnelPresent: ["would want", "would want", "would want", "would want", "would want", "would want"],
      subjonctifPresent: ["(that I) want", "(that you) want", "(that he) want", "(that we) want", "(that you) want", "(that they) want"],
    },
  },
  devoir: {
    infinitive: "devoir",
    english: "must / to have to",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["dois", "dois", "doit", "devons", "devez", "doivent"],
      passeCompose: ["ai dû", "as dû", "a dû", "avons dû", "avez dû", "ont dû"],
      imparfait: ["devais", "devais", "devait", "devions", "deviez", "devaient"],
      futurSimple: ["devrai", "devras", "devra", "devrons", "devrez", "devront"],
      conditionnelPresent: ["devrais", "devrais", "devrait", "devrions", "devriez", "devraient"],
      subjonctifPresent: ["doive", "doives", "doive", "devions", "deviez", "doivent"],
    },
    tensesEn: {
      present: ["must/have to", "must/have to", "must/has to", "must/have to", "must/have to", "must/have to"],
      passeCompose: ["had to", "had to", "had to", "had to", "had to", "had to"],
      imparfait: ["had to/used to have to", "had to/used to have to", "had to/used to have to", "had to/used to have to", "had to/used to have to", "had to/used to have to"],
      futurSimple: ["will have to", "will have to", "will have to", "will have to", "will have to", "will have to"],
      conditionnelPresent: ["should/would have to", "should/would have to", "should/would have to", "should/would have to", "should/would have to", "should/would have to"],
      subjonctifPresent: ["(that I) must", "(that you) must", "(that he) must", "(that we) must", "(that you) must", "(that they) must"],
    },
  },
  savoir: {
    infinitive: "savoir",
    english: "to know (fact)",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["sais", "sais", "sait", "savons", "savez", "savent"],
      passeCompose: ["ai su", "as su", "a su", "avons su", "avez su", "ont su"],
      imparfait: ["savais", "savais", "savait", "savions", "saviez", "savaient"],
      futurSimple: ["saurai", "sauras", "saura", "saurons", "saurez", "sauront"],
      conditionnelPresent: ["saurais", "saurais", "saurait", "saurions", "sauriez", "sauraient"],
      subjonctifPresent: ["sache", "saches", "sache", "sachions", "sachiez", "sachent"],
    },
    tensesEn: {
      present: ["know", "know", "knows", "know", "know", "know"],
      passeCompose: ["knew/found out", "knew/found out", "knew/found out", "knew/found out", "knew/found out", "knew/found out"],
      imparfait: ["knew/used to know", "knew/used to know", "knew/used to know", "knew/used to know", "knew/used to know", "knew/used to know"],
      futurSimple: ["will know", "will know", "will know", "will know", "will know", "will know"],
      conditionnelPresent: ["would know", "would know", "would know", "would know", "would know", "would know"],
      subjonctifPresent: ["(that I) know", "(that you) know", "(that he) know", "(that we) know", "(that you) know", "(that they) know"],
    },
  },
  venir: {
    infinitive: "venir",
    english: "to come",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    usesEtre: true,
    tenses: {
      present: ["viens", "viens", "vient", "venons", "venez", "viennent"],
      passeCompose: ["suis venu(e)", "es venu(e)", "est venu(e)", "sommes venu(e)s", "êtes venu(e)(s)", "sont venu(e)s"],
      imparfait: ["venais", "venais", "venait", "venions", "veniez", "venaient"],
      futurSimple: ["viendrai", "viendras", "viendra", "viendrons", "viendrez", "viendront"],
      conditionnelPresent: ["viendrais", "viendrais", "viendrait", "viendrions", "viendriez", "viendraient"],
      subjonctifPresent: ["vienne", "viennes", "vienne", "venions", "veniez", "viennent"],
    },
    tensesEn: {
      present: ["come", "come", "comes", "come", "come", "come"],
      passeCompose: ["came", "came", "came", "came", "came", "came"],
      imparfait: ["was coming/used to come", "were coming/used to come", "was coming/used to come", "were coming/used to come", "were coming/used to come", "were coming/used to come"],
      futurSimple: ["will come", "will come", "will come", "will come", "will come", "will come"],
      conditionnelPresent: ["would come", "would come", "would come", "would come", "would come", "would come"],
      subjonctifPresent: ["(that I) come", "(that you) come", "(that he) come", "(that we) come", "(that you) come", "(that they) come"],
    },
  },
  prendre: {
    infinitive: "prendre",
    english: "to take",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["prends", "prends", "prend", "prenons", "prenez", "prennent"],
      passeCompose: ["ai pris", "as pris", "a pris", "avons pris", "avez pris", "ont pris"],
      imparfait: ["prenais", "prenais", "prenait", "prenions", "preniez", "prenaient"],
      futurSimple: ["prendrai", "prendras", "prendra", "prendrons", "prendrez", "prendront"],
      conditionnelPresent: ["prendrais", "prendrais", "prendrait", "prendrions", "prendriez", "prendraient"],
      subjonctifPresent: ["prenne", "prennes", "prenne", "prenions", "preniez", "prennent"],
    },
    tensesEn: {
      present: ["take", "take", "takes", "take", "take", "take"],
      passeCompose: ["took", "took", "took", "took", "took", "took"],
      imparfait: ["was taking/used to take", "were taking/used to take", "was taking/used to take", "were taking/used to take", "were taking/used to take", "were taking/used to take"],
      futurSimple: ["will take", "will take", "will take", "will take", "will take", "will take"],
      conditionnelPresent: ["would take", "would take", "would take", "would take", "would take", "would take"],
      subjonctifPresent: ["(that I) take", "(that you) take", "(that he) take", "(that we) take", "(that you) take", "(that they) take"],
    },
  },
  parler: {
    infinitive: "parler",
    english: "to speak",
    group: "1er groupe",
    groupNum: 1,
    importance: 3,
    tenses: {
      present: ["parle", "parles", "parle", "parlons", "parlez", "parlent"],
      passeCompose: ["ai parlé", "as parlé", "a parlé", "avons parlé", "avez parlé", "ont parlé"],
      imparfait: ["parlais", "parlais", "parlait", "parlions", "parliez", "parlaient"],
      futurSimple: ["parlerai", "parleras", "parlera", "parlerons", "parlerez", "parleront"],
      conditionnelPresent: ["parlerais", "parlerais", "parlerait", "parlerions", "parleriez", "parleraient"],
      subjonctifPresent: ["parle", "parles", "parle", "parlions", "parliez", "parlent"],
    },
    tensesEn: {
      present: ["speak", "speak", "speaks", "speak", "speak", "speak"],
      passeCompose: ["spoke", "spoke", "spoke", "spoke", "spoke", "spoke"],
      imparfait: ["was speaking/used to speak", "were speaking/used to speak", "was speaking/used to speak", "were speaking/used to speak", "were speaking/used to speak", "were speaking/used to speak"],
      futurSimple: ["will speak", "will speak", "will speak", "will speak", "will speak", "will speak"],
      conditionnelPresent: ["would speak", "would speak", "would speak", "would speak", "would speak", "would speak"],
      subjonctifPresent: ["(that I) speak", "(that you) speak", "(that he) speak", "(that we) speak", "(that you) speak", "(that they) speak"],
    },
  },
  finir: {
    infinitive: "finir",
    english: "to finish",
    group: "2ème groupe",
    groupNum: 2,
    importance: 3,
    tenses: {
      present: ["finis", "finis", "finit", "finissons", "finissez", "finissent"],
      passeCompose: ["ai fini", "as fini", "a fini", "avons fini", "avez fini", "ont fini"],
      imparfait: ["finissais", "finissais", "finissait", "finissions", "finissiez", "finissaient"],
      futurSimple: ["finirai", "finiras", "finira", "finirons", "finirez", "finiront"],
      conditionnelPresent: ["finirais", "finirais", "finirait", "finirions", "finiriez", "finiraient"],
      subjonctifPresent: ["finisse", "finisses", "finisse", "finissions", "finissiez", "finissent"],
    },
    tensesEn: {
      present: ["finish", "finish", "finishes", "finish", "finish", "finish"],
      passeCompose: ["finished", "finished", "finished", "finished", "finished", "finished"],
      imparfait: ["was finishing/used to finish", "were finishing/used to finish", "was finishing/used to finish", "were finishing/used to finish", "were finishing/used to finish", "were finishing/used to finish"],
      futurSimple: ["will finish", "will finish", "will finish", "will finish", "will finish", "will finish"],
      conditionnelPresent: ["would finish", "would finish", "would finish", "would finish", "would finish", "would finish"],
      subjonctifPresent: ["(that I) finish", "(that you) finish", "(that he) finish", "(that we) finish", "(that you) finish", "(that they) finish"],
    },
  },
  manger: {
    infinitive: "manger",
    english: "to eat",
    group: "1er groupe",
    groupNum: 1,
    importance: 3,
    tenses: {
      present: ["mange", "manges", "mange", "mangeons", "mangez", "mangent"],
      passeCompose: ["ai mangé", "as mangé", "a mangé", "avons mangé", "avez mangé", "ont mangé"],
      imparfait: ["mangeais", "mangeais", "mangeait", "mangions", "mangiez", "mangeaient"],
      futurSimple: ["mangerai", "mangeras", "mangera", "mangerons", "mangerez", "mangeront"],
      conditionnelPresent: ["mangerais", "mangerais", "mangerait", "mangerions", "mangeriez", "mangeraient"],
      subjonctifPresent: ["mange", "manges", "mange", "mangions", "mangiez", "mangent"],
    },
    tensesEn: {
      present: ["eat", "eat", "eats", "eat", "eat", "eat"],
      passeCompose: ["ate", "ate", "ate", "ate", "ate", "ate"],
      imparfait: ["was eating/used to eat", "were eating/used to eat", "was eating/used to eat", "were eating/used to eat", "were eating/used to eat", "were eating/used to eat"],
      futurSimple: ["will eat", "will eat", "will eat", "will eat", "will eat", "will eat"],
      conditionnelPresent: ["would eat", "would eat", "would eat", "would eat", "would eat", "would eat"],
      subjonctifPresent: ["(that I) eat", "(that you) eat", "(that he) eat", "(that we) eat", "(that you) eat", "(that they) eat"],
    },
  },
  voir: {
    infinitive: "voir",
    english: "to see",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["vois", "vois", "voit", "voyons", "voyez", "voient"],
      passeCompose: ["ai vu", "as vu", "a vu", "avons vu", "avez vu", "ont vu"],
      imparfait: ["voyais", "voyais", "voyait", "voyions", "voyiez", "voyaient"],
      futurSimple: ["verrai", "verras", "verra", "verrons", "verrez", "verront"],
      conditionnelPresent: ["verrais", "verrais", "verrait", "verrions", "verriez", "verraient"],
      subjonctifPresent: ["voie", "voies", "voie", "voyions", "voyiez", "voient"],
    },
    tensesEn: {
      present: ["see", "see", "sees", "see", "see", "see"],
      passeCompose: ["saw", "saw", "saw", "saw", "saw", "saw"],
      imparfait: ["was seeing/used to see", "were seeing/used to see", "was seeing/used to see", "were seeing/used to see", "were seeing/used to see", "were seeing/used to see"],
      futurSimple: ["will see", "will see", "will see", "will see", "will see", "will see"],
      conditionnelPresent: ["would see", "would see", "would see", "would see", "would see", "would see"],
      subjonctifPresent: ["(that I) see", "(that you) see", "(that he) see", "(that we) see", "(that you) see", "(that they) see"],
    },
  },
  dire: {
    infinitive: "dire",
    english: "to say / to tell",
    group: "3ème groupe",
    groupNum: 3,
    importance: 2,
    tenses: {
      present: ["dis", "dis", "dit", "disons", "dites", "disent"],
      passeCompose: ["ai dit", "as dit", "a dit", "avons dit", "avez dit", "ont dit"],
      imparfait: ["disais", "disais", "disait", "disions", "disiez", "disaient"],
      futurSimple: ["dirai", "diras", "dira", "dirons", "direz", "diront"],
      conditionnelPresent: ["dirais", "dirais", "dirait", "dirions", "diriez", "diraient"],
      subjonctifPresent: ["dise", "dises", "dise", "disions", "disiez", "disent"],
    },
    tensesEn: {
      present: ["say/tell", "say/tell", "says/tells", "say/tell", "say/tell", "say/tell"],
      passeCompose: ["said/told", "said/told", "said/told", "said/told", "said/told", "said/told"],
      imparfait: ["was saying/used to say", "were saying/used to say", "was saying/used to say", "were saying/used to say", "were saying/used to say", "were saying/used to say"],
      futurSimple: ["will say/tell", "will say/tell", "will say/tell", "will say/tell", "will say/tell", "will say/tell"],
      conditionnelPresent: ["would say/tell", "would say/tell", "would say/tell", "would say/tell", "would say/tell", "would say/tell"],
      subjonctifPresent: ["(that I) say", "(that you) say", "(that he) say", "(that we) say", "(that you) say", "(that they) say"],
    },
  },
  aimer: {
    infinitive: "aimer",
    english: "to love / to like",
    group: "1er groupe",
    groupNum: 1,
    importance: 3,
    startsWithVowel: true,
    tenses: {
      present: ["aime", "aimes", "aime", "aimons", "aimez", "aiment"],
      passeCompose: ["ai aimé", "as aimé", "a aimé", "avons aimé", "avez aimé", "ont aimé"],
      imparfait: ["aimais", "aimais", "aimait", "aimions", "aimiez", "aimaient"],
      futurSimple: ["aimerai", "aimeras", "aimera", "aimerons", "aimerez", "aimeront"],
      conditionnelPresent: ["aimerais", "aimerais", "aimerait", "aimerions", "aimeriez", "aimeraient"],
      subjonctifPresent: ["aime", "aimes", "aime", "aimions", "aimiez", "aiment"],
    },
    tensesEn: {
      present: ["love/like", "love/like", "loves/likes", "love/like", "love/like", "love/like"],
      passeCompose: ["loved/liked", "loved/liked", "loved/liked", "loved/liked", "loved/liked", "loved/liked"],
      imparfait: ["was loving/used to love", "were loving/used to love", "was loving/used to love", "were loving/used to love", "were loving/used to love", "were loving/used to love"],
      futurSimple: ["will love/like", "will love/like", "will love/like", "will love/like", "will love/like", "will love/like"],
      conditionnelPresent: ["would love/like", "would love/like", "would love/like", "would love/like", "would love/like", "would love/like"],
      subjonctifPresent: ["(that I) love", "(that you) love", "(that he) love", "(that we) love", "(that you) love", "(that they) love"],
    },
  },
  partir: {
    infinitive: "partir",
    english: "to leave",
    group: "3ème groupe",
    groupNum: 3,
    importance: 3,
    usesEtre: true,
    tenses: {
      present: ["pars", "pars", "part", "partons", "partez", "partent"],
      passeCompose: ["suis parti(e)", "es parti(e)", "est parti(e)", "sommes parti(e)s", "êtes parti(e)(s)", "sont parti(e)s"],
      imparfait: ["partais", "partais", "partait", "partions", "partiez", "partaient"],
      futurSimple: ["partirai", "partiras", "partira", "partirons", "partirez", "partiront"],
      conditionnelPresent: ["partirais", "partirais", "partirait", "partirions", "partiriez", "partiraient"],
      subjonctifPresent: ["parte", "partes", "parte", "partions", "partiez", "partent"],
    },
    tensesEn: {
      present: ["leave", "leave", "leaves", "leave", "leave", "leave"],
      passeCompose: ["left", "left", "left", "left", "left", "left"],
      imparfait: ["was leaving/used to leave", "were leaving/used to leave", "was leaving/used to leave", "were leaving/used to leave", "were leaving/used to leave", "were leaving/used to leave"],
      futurSimple: ["will leave", "will leave", "will leave", "will leave", "will leave", "will leave"],
      conditionnelPresent: ["would leave", "would leave", "would leave", "would leave", "would leave", "would leave"],
      subjonctifPresent: ["(that I) leave", "(that you) leave", "(that he) leave", "(that we) leave", "(that you) leave", "(that they) leave"],
    },
  },
  mettre: {
    infinitive: "mettre",
    english: "to put",
    group: "3ème groupe",
    groupNum: 3,
    importance: 3,
    tenses: {
      present: ["mets", "mets", "met", "mettons", "mettez", "mettent"],
      passeCompose: ["ai mis", "as mis", "a mis", "avons mis", "avez mis", "ont mis"],
      imparfait: ["mettais", "mettais", "mettait", "mettions", "mettiez", "mettaient"],
      futurSimple: ["mettrai", "mettras", "mettra", "mettrons", "mettrez", "mettront"],
      conditionnelPresent: ["mettrais", "mettrais", "mettrait", "mettrions", "mettriez", "mettraient"],
      subjonctifPresent: ["mette", "mettes", "mette", "mettions", "mettiez", "mettent"],
    },
    tensesEn: {
      present: ["put", "put", "puts", "put", "put", "put"],
      passeCompose: ["put", "put", "put", "put", "put", "put"],
      imparfait: ["was putting/used to put", "were putting/used to put", "was putting/used to put", "were putting/used to put", "were putting/used to put", "were putting/used to put"],
      futurSimple: ["will put", "will put", "will put", "will put", "will put", "will put"],
      conditionnelPresent: ["would put", "would put", "would put", "would put", "would put", "would put"],
      subjonctifPresent: ["(that I) put", "(that you) put", "(that he) put", "(that we) put", "(that you) put", "(that they) put"],
    },
  },
  attendre: {
    infinitive: "attendre",
    english: "to wait",
    group: "3ème groupe",
    groupNum: 3,
    importance: 3,
    startsWithVowel: true,
    tenses: {
      present: ["attends", "attends", "attend", "attendons", "attendez", "attendent"],
      passeCompose: ["ai attendu", "as attendu", "a attendu", "avons attendu", "avez attendu", "ont attendu"],
      imparfait: ["attendais", "attendais", "attendait", "attendions", "attendiez", "attendaient"],
      futurSimple: ["attendrai", "attendras", "attendra", "attendrons", "attendrez", "attendront"],
      conditionnelPresent: ["attendrais", "attendrais", "attendrait", "attendrions", "attendriez", "attendraient"],
      subjonctifPresent: ["attende", "attendes", "attende", "attendions", "attendiez", "attendent"],
    },
    tensesEn: {
      present: ["wait", "wait", "waits", "wait", "wait", "wait"],
      passeCompose: ["waited", "waited", "waited", "waited", "waited", "waited"],
      imparfait: ["was waiting/used to wait", "were waiting/used to wait", "was waiting/used to wait", "were waiting/used to wait", "were waiting/used to wait", "were waiting/used to wait"],
      futurSimple: ["will wait", "will wait", "will wait", "will wait", "will wait", "will wait"],
      conditionnelPresent: ["would wait", "would wait", "would wait", "would wait", "would wait", "would wait"],
      subjonctifPresent: ["(that I) wait", "(that you) wait", "(that he) wait", "(that we) wait", "(that you) wait", "(that they) wait"],
    },
  },
};

const TIPS = [
  "Short daily sessions beat long cramming!",
  "Try writing sentences with new conjugations.",
  "Focus on être and avoir first — they're everywhere!",
  "The nous and vous forms often rhyme.",
  "Passé composé = avoir/être + past participle.",
  "Imparfait is for descriptions and habits.",
  "Subjonctif follows 'que' — que je sois...",
  "Conditional is like future stem + imparfait endings.",
  "Most -er verbs follow the same pattern!",
  "Practice speaking out loud for better memory.",
];

const ENCOURAGEMENTS = {
  correct: ["Parfait!", "Magnifique!", "Excellent!", "Bravo!", "Très bien!", "Super!", "C'est ça!", "Formidable!"],
  streak: ["You're on fire!", "Keep going!", "Unstoppable!", "Incroyable streak!"],
  levelUp: ["Level up!", "New level unlocked!", "You're making progress!"],
};
